/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Thu Jan 12 13:54:22 EST 2017
Thu Jan 12 13:54:22 EST 2017
Thu Jan 12 13:54:22 EST 2017
Thu Jan 12 13:54:22 EST 2017
c22b-s2.ufhpc
c22b-s2.ufhpc
c22b-s2.ufhpc
c22b-s2.ufhpc
Thu Jan 12 13:54:22 EST 2017
c22b-s23.ufhpc
Thu Jan 12 13:54:22 EST 2017
Thu Jan 12 13:54:22 EST 2017
c31b-s8.ufhpc
c31b-s8.ufhpc
Thu Jan 12 13:54:22 EST 2017
c22a-s25.ufhpc
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Will run DY NLO job with parameter =  8
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Will run DY NLO job with parameter =  2
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Will run DY NLO job with parameter =  1
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Will run DY NLO job with parameter =  4
Will run DY NLO job with parameter =  3
Traceback (most recent call last):
  File "scripts/get_sects.py", line 9, in <module>
    print getsects(sys.argv[1], sys.argv[2].upper())
  File "/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin/scripts/defs.py", line 187, in getsects
    raise IOError
IOError
Traceback (most recent call last):
  File "scripts/get_scalevar.py", line 9, in <module>
    scalevars = getscalevar(sys.argv[1])
  File "/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin/scripts/defs.py", line 254, in getscalevar
    return [[muf,mur],[muf,mur],False]
UnboundLocalError: local variable 'muf' referenced before assignment
./local_run.sh: line 66: [: illegal: integer expression expected
./local_run.sh: line 67: [: too many arguments
./local_run.sh: line 71: [: illegal: integer expression expected
./local_run.sh: line 71: [: too many arguments
./local_run.sh: line 81: [: illegal: integer expression expected
./local_run.sh: line 82: [: too many arguments
./local_run.sh: line 83: [: too many arguments
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
illegal input of getsects()
Error reading input file.
Working in /ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin
Will run DY NLO job with parameter =  7
Will run DY NLO job with parameter =  5
Will run DY NLO job with parameter =  6
Traceback (most recent call last):
  File "scripts/create_parallel.py", line 68, in <module>
    sectors = getsects(sys.argv[2], sys.argv[1].upper())
  File "/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin/scripts/defs.py", line 187, in getsects
    raise IOError
IOError
Traceback (most recent call last):
  File "scripts/get_sects.py", line 9, in <module>
    print getsects(sys.argv[1], sys.argv[2].upper())
  File "/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin/scripts/defs.py", line 170, in getsects
    fin = open(str(namestr), 'r')
IOError: [Errno 2] No such file or directory: 'mu13tev-higgs-110-310-full-input.txt'
Traceback (most recent call last):
  File "scripts/get_scalevar.py", line 9, in <module>
    scalevars = getscalevar(sys.argv[1])
  File "/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin/scripts/defs.py", line 219, in getscalevar
    fin = open(infile, 'r')
IOError: [Errno 2] No such file or directory: 'mu13tev-higgs-110-310-full-input.txt'
./local_run.sh: line 66: [: illegal: integer expression expected
./local_run.sh: line 67: [: too many arguments
./local_run.sh: line 71: [: illegal: integer expression expected
./local_run.sh: line 71: [: too many arguments
./local_run.sh: line 81: [: illegal: integer expression expected
./local_run.sh: line 82: [: too many arguments
./local_run.sh: line 83: [: too many arguments
illegal input of getsects()
Error reading input file.
Traceback (most recent call last):
  File "scripts/create_parallel.py", line 68, in <module>
    sectors = getsects(sys.argv[2], sys.argv[1].upper())
  File "/ufrc/avery/bregnery/FEWZforHiggs2mumu/FEWZ/FEWZ_3.1.b2/bin/scripts/defs.py", line 170, in getsects
    fin = open(str(namestr), 'r')
IOError: [Errno 2] No such file or directory: 'mu13tev-higgs-110-310-full-input.txt'
Traceback (most recent call last):
Traceback (most recent call last):
  File "scripts/get_bin_files.py", line 22, in <module>
Using 1 parallel threads
Using 1 parallel threads
Starting sector 1 ...
Starting sector 1 ...
  File "scripts/get_bin_files.py", line 22, in <module>
Using 1 parallel threads
Using 1 parallel threads
Using 1 parallel threads
    newfile = open(newfilen, 'w')
    Starting sector 1 ...
Starting sector 1 ...
Starting sector 1 ...
IOErrornewfile = open(newfilen, 'w')
: Using 1 parallel threads
IOErrorStarting sector 1 ...
[Errno 20] Not a directory: 'mu13tev-higgs-110-160-1jet/mu13tev-higgs-110-160-1jet-histograms.txt': 
[Errno 20] Not a directory: 'mu13tev-higgs-110-310-full/mu13tev-higgs-110-310-full-histograms.txt'
cp: cannot stat `mu13tev-higgs-110-310-full-input.txt': No such file or directory
./local_run.sh: line 125: cd: mu13tev-higgs-110-310-full: Not a directory
Using 1 parallel threads
./local_run.sh: line 152: [: 1: unary operator expected
Job finished in 0 seconds
Run the following to post-process the output files: finish.sh mu13tev-higgs-110-310-full <order>.mu13tev-higgs-110-310-full-results.dat
Thu Jan 12 13:54:24 EST 2017
./local_run.sh: line 125: cd: mu13tev-higgs-110-160-1jet: Not a directory
Using 1 parallel threads
./local_run.sh: line 152: [: 1: unary operator expected
Job finished in 0 seconds
Run the following to post-process the output files: finish.sh mu13tev-higgs-110-160-1jet <order>.mu13tev-higgs-110-160-1jet-results.dat
Thu Jan 12 13:54:24 EST 2017
